version: '3.8'

services:
  postgres:
    container_name: mv-postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030
      POSTGRES_DB: mo_vendas_db
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres-db:
    driver: local